# Generated by Django 5.2 on 2026-04-23 22:15

import apps.beneficios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
            ],
            options={
                'verbose_name': 'categoria de beneficio',
                'verbose_name_plural': 'categorias de beneficios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('descripcion_corta', models.CharField(max_length=250, verbose_name='descripcion corta')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.beneficios.models.beneficio_image_upload_to, verbose_name='imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado')),
                ('vigencia', models.DateField(blank=True, help_text='Fecha hasta la que el beneficio se considera vigente.', null=True, verbose_name='vigencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficios', to='beneficios.categoriabeneficio', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'beneficio',
                'verbose_name_plural': 'beneficios',
                'ordering': ['-destacado', 'titulo'],
            },
        ),
    ]
