# Generated by Django 6.0 on 2026-05-16 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
            ],
            options={
                'verbose_name': 'categoria de capacitacion',
                'verbose_name_plural': 'categorias de capacitacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('descripcion_corta', models.CharField(max_length=250, verbose_name='descripcion corta')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='capacitacion/', verbose_name='imagen')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrida', 'Hibrida')], default='presencial', max_length=20, verbose_name='modalidad')),
                ('duracion', models.CharField(help_text='Ej: "8 horas", "2 dias"', max_length=80, verbose_name='duracion')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('cupos', models.IntegerField(default=0, verbose_name='cupos')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitaciones', to='capacitacion.categoriacapacitacion', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'capacitacion',
                'verbose_name_plural': 'capacitaciones',
                'ordering': ['fecha', 'titulo'],
            },
        ),
    ]
