# Generated by Django 6.0 on 2026-05-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('video', 'Video tutorial'), ('pdf', 'Instructivo PDF'), ('guia', 'Guia rapida'), ('presencial', 'Capacitacion presencial')], max_length=20)),
                ('url_video', models.URLField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='ayuda/')),
                ('fecha_presencial', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso de ayuda',
                'verbose_name_plural': 'Centro de ayuda',
                'ordering': ['orden', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='TipoAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de ayuda',
                'verbose_name_plural': 'Tipos de ayuda',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Capacitacion',
        ),
        migrations.DeleteModel(
            name='CategoriaCapacitacion',
        ),
    ]
