# Generated by Django 5.2 on 2026-04-23 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('asunto', models.CharField(max_length=150, verbose_name='asunto')),
                ('mensaje', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'El mensaje debe tener al menos 10 caracteres.')], verbose_name='mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='leido')),
                ('respondido', models.BooleanField(default=False, verbose_name='respondido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recibido')),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['leido', '-created_at'],
            },
        ),
    ]
