# Generated by Django 5.2 on 2026-04-23 22:15

import apps.siteconfig.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, verbose_name='nombre del sitio')),
                ('site_tagline', models.CharField(blank=True, max_length=200, verbose_name='bajada del sitio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.siteconfig.models.siteconfig_upload_to, verbose_name='logo')),
                ('primary_color', models.CharField(default='#0F4C5C', help_text='Color institucional principal en formato hexadecimal.', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal valido, por ejemplo #0F4C5C.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='color principal')),
                ('secondary_color', models.CharField(default='#1F2937', help_text='Color secundario en formato hexadecimal.', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal valido, por ejemplo #0F4C5C.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='color secundario')),
                ('accent_color', models.CharField(default='#EAB308', help_text='Color de apoyo para llamados a la accion.', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal valido, por ejemplo #0F4C5C.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='color de acento')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='telefono de contacto')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='direccion')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('x_url', models.URLField(blank=True, verbose_name='X / Twitter')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('hero_title', models.CharField(blank=True, max_length=160, verbose_name='titulo hero')),
                ('hero_text', models.TextField(blank=True, verbose_name='texto hero')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=apps.siteconfig.models.siteconfig_upload_to, verbose_name='imagen hero')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'configuracion del sitio',
                'verbose_name_plural': 'configuracion del sitio',
            },
        ),
    ]
