# Generated by Django 5.2 on 2026-04-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descripcion breve para SEO y navegadores.', max_length=255, verbose_name='meta descripcion'),
        ),
    ]
