# Generated by Django 5.2 on 2026-04-23 22:15

import apps.documentos.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
            ],
            options={
                'verbose_name': 'categoria de documento',
                'verbose_name_plural': 'categorias de documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('archivo', models.FileField(upload_to=apps.documentos.models.documento_upload_to, verbose_name='archivo')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='descripcion')),
                ('publico', models.BooleanField(default=True, verbose_name='publico')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.categoriadocumento', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-fecha', 'titulo'],
            },
        ),
    ]
