# Generated by Django 5.2 on 2026-04-23 22:15

import apps.comunicados.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
            ],
            options={
                'verbose_name': 'categoria de comunicado',
                'verbose_name_plural': 'categorias de comunicados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('extracto', models.CharField(max_length=300, verbose_name='extracto')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.comunicados.models.comunicado_image_upload_to, verbose_name='imagen')),
                ('publicado', models.BooleanField(default=False, verbose_name='publicado')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Se usa para ordenar y publicar el comunicado.', verbose_name='fecha de publicacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='comunicados.categoriacomunicado', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'comunicado',
                'verbose_name_plural': 'comunicados',
                'ordering': ['-fecha_publicacion', '-created_at'],
            },
        ),
    ]
